#!/usr/bin/env php
<?php declare(strict_types=1);


/*
 * This file is part of Backfire.
 *
 * (c) Baraa Al-Saqqa <baraa@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

if (!version_compare(PHP_VERSION, PHP_VERSION, '=')) {
    fwrite(
        STDERR,
        sprintf(
            '%s declares an invalid value for PHP_VERSION.' . PHP_EOL .
            'This breaks fundamental functionality such as version_compare().' . PHP_EOL .
            'Please use a different PHP interpreter.' . PHP_EOL,

            PHP_BINARY
        )
    );

    die(1);
}

if (version_compare('8.0.0', PHP_VERSION, '>')) {
    fwrite(
        STDERR,
        sprintf(
            'This version of Backfire requires PHP >= 8.0.' . PHP_EOL .
            'You are using PHP %s (%s).' . PHP_EOL,
            PHP_VERSION,
            PHP_BINARY
        )
    );

    die(1);
}

if (!ini_get('date.timezone')) {
    ini_set('date.timezone', 'UTC');
}

# set current directory
chdir(__DIR__);

# if vendor/autoload.php not found and call install command, run composer install
# get args
$argv = $_SERVER['argv'];
if (!file_exists(__DIR__ . '/vendor/autoload.php') && in_array('install', $argv)) {

    fwrite(
        STDERR,
        sprintf(
            'We running "composer install" on current package folder.' . PHP_EOL
        )
    );
    # run composer install
    passthru(' composer install');

    echo "\n\033[32mDependency installed successfully!\033[0m\n\r" . PHP_EOL;

}

if (file_exists(__DIR__ . '/vendor/autoload.php') && in_array('update', $argv)) {

    fwrite(
        STDERR,
        sprintf(
            'We running "composer update" on current package folder.' . PHP_EOL
        )
    );
    # run composer update
    passthru(' composer update');

    echo "\n\033[32mDependency updated successfully!\033[0m\n\r" . PHP_EOL;
}

$isInstalled = false;

if (file_exists( __DIR__ . '/vendor/autoload.php')) {
    define('BACKFIRE_COMPOSER_INSTALL',  __DIR__ . '/vendor/autoload.php');
    $isInstalled = true;
}

if ( !$isInstalled ) {
    fwrite(
        STDERR,
        sprintf(
            PHP_EOL .'Please run "backfire install" to install package.' . PHP_EOL. PHP_EOL
        )
    );
    die(1);
}



require BACKFIRE_COMPOSER_INSTALL;
require __DIR__ . '\src\bootstrap.php';
